apiVersion: v1
kind: Pod
metadata:
  name: pod-postgres-teste
  labels:
    app: postgres-pod
spec:
  containers:
    - name: postgres-container
      image: uiuq/teste-postgres:0.1
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: db-configmap